apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: $MY_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        azureDNS:
          hostedZoneName: ${DOMAIN}
          resourceGroupName: ${NAME}
          subscriptionID: ${ARM_SUBSCRIPTION_ID}
          environment: AzurePublicCloud
          managedIdentity:
            clientID: ${SERVICE_ACCOUNT_DNS}