apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
  namespace: external-dns
type: Opaque
stringData:
  azure.json: |
    {
      "tenantId": "${ARM_TENANT_ID}",
      "subscriptionId": "${ARM_SUBSCRIPTION_ID}",
      "resourceGroup": "${NAME}",
      "useWorkloadIdentityExtension": true
    }