ingress:
  enabled: true
  className: istio
  hosts:
  - host: httpbin.jm2.infra-gcp.rasa-dev.io
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: httpbin-tls
    hosts: 
    - httpbin.jm2.infra-gcp.rasa-dev.io