kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: $NAME-assistant
  namespace: istio-system
spec:
  commonName: assistant.$DOMAIN
  dnsNames:
    - assistant.$DOMAIN
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  renewBefore: 360h0m0s
  secretName: $NAME-assistant-tls
  usages:
    - server auth
    - client auth