apiVersion: v1
kind: Pod
metadata:
  name: db-init
spec:
  containers:
    - name: db-init
      image: postgres:$PG_VERSION
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/bash"
        - "-ec"
        - "--"
      args:
        - |
          echo "create assistant database and user"
          echo "CREATE USER $DB_ASSISTANT_USERNAME;" | psql -qtAX --set=sslmode=require
          echo "GRANT rds_iam TO $DB_ASSISTANT_USERNAME;" | psql -qtAX --set=sslmode=require
          echo "CREATE DATABASE $DB_ASSISTANT_DATABASE WITH ENCODING = 'UTF8';" | psql -qtAX --set=sslmode=require
          echo "GRANT ALL PRIVILEGES ON DATABASE $DB_ASSISTANT_DATABASE TO $DB_ASSISTANT_USERNAME;" | psql -qtAX --set=sslmode=require
          echo "ALTER DATABASE $DB_ASSISTANT_DATABASE OWNER TO $DB_ASSISTANT_USERNAME;" | psql -qtAX --set=sslmode=require

          echo "create studio database and user"
          echo "CREATE USER $DB_STUDIO_USERNAME WITH PASSWORD '$DB_STUDIO_PASSWORD';" | psql -qtAX --set=sslmode=require
          echo "CREATE DATABASE $DB_STUDIO_DATABASE WITH ENCODING = 'UTF8';" | psql -qtAX --set=sslmode=require
          echo "GRANT ALL PRIVILEGES ON DATABASE $DB_STUDIO_DATABASE TO $DB_STUDIO_USERNAME;" | psql -qtAX --set=sslmode=require
          echo "ALTER DATABASE $DB_STUDIO_DATABASE OWNER TO $DB_STUDIO_USERNAME;" | psql -qtAX --set=sslmode=require

          echo "create Keycloak database and user"
          echo "CREATE DATABASE $DB_KEYCLOAK_DATABASE WITH ENCODING = 'UTF8';" | psql -qtAX --set=sslmode=require
          echo "GRANT ALL PRIVILEGES ON DATABASE $DB_KEYCLOAK_DATABASE TO $DB_STUDIO_USERNAME;" | psql -qtAX --set=sslmode=require
          echo "ALTER DATABASE $DB_KEYCLOAK_DATABASE OWNER TO $DB_STUDIO_USERNAME;" | psql -qtAX --set=sslmode=require

          echo "granting schema public to keycloak user role..."
          echo "GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_STUDIO_USERNAME;" | psql -qtAX --set=sslmode=require
          echo "granted schema public to keycloak"

          sleep 10
          echo "done"
      env:
        - name: PGHOST
          value: $DB_HOST
        - name: PGUSER
          value: $DB_ROOT_UN
        - name: PGPASSWORD
          value: "$DB_ROOT_PW"
        - name: PGPORT
          value: "$DB_PORT"
  restartPolicy: Never