serviceAccount:
  create: true
  name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: $NAME-dns@$PROJECT_ID.iam.gserviceaccount.com

rbac:
  create: true

policy: sync

sources:
  - istio-gateway
  - ingress

txtOwnerId: $NAME

provider: 
  name: google

extraArgs:
  - --google-project=$PROJECT_ID

domainFilters:
  - $DOMAIN