serviceAccount:
  create: true
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: $SERVICE_ACCOUNT_DNS

rbac:
  create: true

policy: sync

sources:
  - istio-gateway
  - ingress

txtOwnerId: $NAME

provider: 
  name: aws

env:
  - name: AWS_DEFAULT_REGION
    value: $REGION

domainFilters:
  - $DOMAIN